name: Speedtest
on: workflow_dispatch

jobs:
  test-speed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install speedtest
        run: sudo apt-get update -y && sudo apt-get install -y speedtest-cli

      - name: Run speedtest
        run: |
          cd $GITHUB_WORKSPACE
          file_name=$(date -Iseconds)
          speedtest --simple > runs/$file_name
          git config user.name github-actions
          git add .
          git commit -m "New run"
          git push
